---
title: 'Problem 3: Analysis of faithful datasets.'
author: 'Name : Sanjay Kumar Sinha   Roll Number : MDS202230'
output:
  word_document: default
  html_document: default
---


Consider the `faithful` datasets:
```{r message=FALSE, warning=FALSE}
attach(faithful)
waiting = sort(waiting)
hist(faithful$waiting,xlab = 'waiting',probability = T,col='pink',main='')
```

Fit following three models using MLE method and calculate **Akaike information criterion** (aka., AIC) for each fitted model. Based on AIC decides which model is the best model? Based on the best model calculate the following probability
$$
\mathbb{P}(60<\texttt{waiting}<70)
$$

(i) **Model 1**:
$$
f(x)=p*Gamma(x|\alpha,\sigma_1)+(1-p)N(x|\mu,\sigma_2^2),~~0<p<1
$$
```{r}
# Method 1

NegLogLike1 <- function(theta,data){
  alpha1 = exp(theta[1])
  beta1 = exp(theta[2])
  mu2 = theta[3]
  sigma2 = exp(theta[4])
  p = exp(theta[5])/(1+exp(theta[5]))
  n = length(data)
  l=0
  for(i in 1:n){
    l = l + log(p*dgamma(data[i],shape = alpha1,scale= beta1)
                +(1-p)*dnorm(data[i], mean=mu2, sd= sigma2))
  }
  return(-l)
}
#length(waiting[waiting<67])/ length(waiting)
theta1_initial=c(log(89.05),log(0.61),80.21,log(5.70),-0.58)  

#NegLogLikeMix(theta_initial,waiting)


fit1 = optim(theta1_initial
            ,NegLogLike1
            ,data=waiting)

theta1_hat = fit1$par
alpha11_hat = exp(theta1_hat[1])
beta11_hat = exp(theta1_hat[2])
mu12_hat = theta1_hat[3]
sigma12_hat = exp(theta1_hat[4])
p1_hat = exp(theta1_hat[5])/(1+exp(theta1_hat[5]))

d_mle1 = p1_hat*dgamma(waiting,shape = alpha11_hat, scale = beta11_hat)+(1-p1_hat)*dnorm(waiting,mean=mu12_hat,sd=sigma12_hat)


hist(faithful$waiting,xlab = 'waiting',
     probability = T,col='pink',main='' ,ylim=c(0.,0.05))
lines(waiting,d_mle1,lwd=3,col='red')

```

(ii) **Model 2**:
$$
f(x)=p*Gamma(x|\alpha_1,\sigma_1)+(1-p)Gamma(x|\alpha_2,\sigma_2),~~0<p<1
$$
```{r}
# Method 2

NegLogLike2 <- function(theta,data){
  alpha1 = exp(theta[1])
  beta1 = exp(theta[2])
  alpha2 = exp(theta[3])
  beta2 = exp(theta[4])
  p = exp(theta[5])/(1+exp(theta[5]))
  n = length(data)
  l=0
  for(i in 1:n){
    l = l + log(p*dgamma(data[i],shape = alpha1,scale = beta1)
                +(1-p)*dgamma(data[i],shape=alpha2,scale =beta2))
  }
  return(-l)
}
#length(waiting[waiting<65])/ length(waiting)

#theta2_initial=c(log(78),log(1.5),log(104),log(1.3),-0.62) #wrong initial values
theta2_initial=c(log(78),log(0.7),log(104),log(0.8),-0.62)


#theta_initial=c(log(89.05),log(0.61),log(198.12),log(0.4),-0.58) #doesn't work interchange parameters and then works
#theta_initial = c(78,1.5,104,1.3,.35)
#NegLogLikeMix(theta_initial,waiting)


fit2 = optim(theta2_initial
            ,NegLogLike2
            ,data=waiting)

theta2_hat = fit2$par
alpha21_hat = exp(theta2_hat[1])
beta21_hat = exp(theta2_hat[2])
alpha22_hat = exp(theta2_hat[3])
beta22_hat = exp(theta2_hat[4])
p2_hat = exp(theta2_hat[5])/(1+exp(theta2_hat[5]))

d_mle2 = p2_hat*dgamma(waiting,shape = alpha21_hat,scale = beta21_hat) +(1-p2_hat)*dgamma(waiting,shape=alpha22_hat,scale=beta22_hat)

hist(faithful$waiting,xlab = 'waiting',
     probability = T,col='pink',main='' ,ylim=c(0.,0.05))
lines(waiting,d_mle2,lwd=3,col='purple')
```

(iii) **Model 3**:
$$
f(x)=p*logNormal(x|\mu_1,\sigma_1^2)+(1-p)logNormal(x|\mu_1,\sigma_1^2),~~0<p<1
$$
```{r}
# Method 3

NegLogLike3 <- function(theta,data){
  mu1 = exp(theta[1])
  sigma1 = exp(theta[2])
  mu2 = exp(theta[3])
  sigma2 = exp(theta[4])
  p = exp(theta[5])/(1+exp(theta[5]))
  n = length(data)
  l=0
  for(i in 1:n){
    l = l + log(p*dlnorm(data[i],mean = mu1, sd=sigma1)
                +(1-p)*dlnorm(data[i], mean=mu2, sd= sigma2))
  }
  return(-l)
}
#length(waiting[waiting<65])/ length(waiting)
theta3_initial=c(1.37,-2.16,1.48,-2.3,-0.62)  

#NegLogLikeMix(theta_initial,waiting)


fit3 = optim(theta3_initial
            ,NegLogLike3
            ,data=waiting)

theta3_hat = fit3$par
mu31_hat = exp(theta3_hat[1])
sigma31_hat = exp(theta3_hat[2])
mu32_hat = exp(theta3_hat[3])
sigma32_hat = exp(theta3_hat[4])
p3_hat = exp(theta3_hat[5])/(1+exp(theta3_hat[5]))

d_mle3 = p3_hat*dlnorm(waiting,mean=mu31_hat, sd=sigma31_hat) +(1-p3_hat)*dlnorm(waiting,mean=mu32_hat,sd=sigma32_hat)

hist(faithful$waiting,xlab = 'waiting',
     probability = T,col='pink',main='' ,ylim=c(0.,0.05))
lines(waiting,d_mle3,lwd=3,col='yellow')

```



```{r}
# AIC



model = list(fit1,fit2,fit3)

frame=data.frame('Model'=c(0),'No_of_parameters'=c(50),
                 'Max_log_likelihood'=c(0))
for (i in 1:length(model)){
  
  #aic = 2*length(model[[i]]$par) + 2 *model[[i]]$value
  
  frame=rbind(frame,c(paste('Model',as.character(i)),as.numeric(length(model[[i]]$par)),
                      -as.numeric(model[[i]]$value)))
}
frame = frame[-1,]
frame$AIC = 2*as.numeric(frame$No_of_parameters) - 2*as.numeric(frame$Max_log_likelihood)


abc = frame[frame$AIC == min(frame$AIC),]

frame[,c('Model','AIC')]

cat(" The best model is : ",abc$Model )

```



```{r}

#Probability calc

dMix<-function(x,theta){
  mu1 = theta[1]
  sigma1 = theta[2]
  mu2 = theta[3]
  sigma2 = theta[4]
  p = theta[5]
  f = p*dlnorm(x,mean = mu1,sd=sigma1)+(1-p)*dlnorm(x,mean=mu2,sd=sigma2)
  return(f)
}

prob = integrate(dMix,60,70,c(mu31_hat,sigma31_hat,mu32_hat,sigma32_hat,p3_hat))

print(paste("Probability (60 < waiting < 70) = ", prob$value))

```









